<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>Melsec</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyTitle>MelsecClient library</AssemblyTitle>
    <Description>Melsec communication protocol</Description>
    <Company>A.Rudenko</Company>
    <Product>MelsecClient</Product>
    <Copyright>Copyright ©  2013</Copyright>
    <AssemblyVersion>2.6.*</AssemblyVersion>
    <NeutralLanguage>ru</NeutralLanguage>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>
</Project>